version: '2'
services:
  bind:
    image: resystit/bind9:latest
    container_name: bind
    restart: always
    ports:
      - "192.168.10.253:53:53"
      - "192.168.10.253:53:53/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/bind:/etc/bind
